default_language_version:
    python: python3
repos:
-   repo: https://github.com/google/yapf
    rev: v0.32.0
    hooks:
    -   id: yapf
        name: yapf
        description: "A formatter for Python files."
        entry: yapf
        args: [-i, -vv, -p] #inplace
        language: python
        types: [python]
        additional_dependencies:
          - "toml"
-   repo: https://github.com/pycqa/isort
    hooks:
        - id: isort
    rev: 5.10.1
# -   repo: https://github.com/pycqa/pylint
#     hooks:
#         - id: pylint
#           entry: pylint
#           args: [mcli]
#           language: python
#           types: [python]
#           require_serial: true
#     rev: v2.12.2
-   repo: local
    hooks:
    -   id: pyright
        name: pyright
        entry: pyright
        language: node
        types: [python]
        pass_filenames: false
        additional_dependencies: ["pyright"]
# -   repo: https://github.com/PyCQA/pydocstyle
#     hooks:
#     -   id: pydocstyle
#         name: pydocstyle
#         entry: pydocstyle
#         language: python
#         types: [python]
#         additional_dependencies:
#           - "toml"
#     rev: 6.1.1
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-docstring-first
    -   id: check-yaml
    -   id: debug-statements
    -   id: requirements-txt-fixer
    -   id: double-quote-string-fixer
